[package]
name = "consume_analytics_metadata"
version = "1.0.0"
edition.workspace = true

[dependencies]
env_logger = { workspace = true }
log = { workspace = true }
mdb = { workspace = true }
syslog = { workspace = true }
