[package]
name = "consume_analytics_metadata"
version = "1.0.0"
edition.workspace = true
publish = false

[dependencies]
libc = { workspace = true }
log = { workspace = true }

acap-logging = { workspace = true }
mdb = { workspace = true }
