# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      default:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
    versioning-strategy: lockfile-only
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
