[package]
name = "axparameter"
version = "0.0.0"
edition.workspace = true
license = "MIT"

[dependencies]
glib = { workspace = true }
glib-sys = { workspace = true }
axparameter-sys = { workspace = true }

[dev-dependencies]
log = { workspace = true }
syslog = { workspace = true }


