[package]
name = "axserialport"
version = "0.0.0"
edition.workspace = true
license = "MIT"

[dependencies]
axserialport-sys = { workspace = true }
glib = { workspace = true }
glib-sys = { workspace = true }
