[package]
name = "acap-vapix"
version = "0.0.0"
edition.workspace = true
description = "VAPIX access for ACAP apps"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/AxisCommunications/acap-rs"
repository = "https://github.com/AxisCommunications/acap-rs"

[dependencies]
anyhow = { workspace = true }
digest_auth = { workspace = true }
diqwest = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
reqwest-websocket = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
url = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true, default-features = true }
tokio = { workspace = true, features = ["full"] }
