[package]
name = "vdoencodeclient"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }

acap-logging = { workspace = true }
vdo-sys = { workspace = true }
