[package]
name = "inspect_env"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
log = { workspace = true }

acap-logging = { workspace = true }

[features]
default = ["acap-logging/default"]
