[package]
name = "vdo"
version = "0.1.0"
edition.workspace = true

[dependencies]
vdo-sys = { workspace = true }
log.workspace = true
anyhow.workspace = true
gobject-sys = "0.20.4"

[features]
device-tests = []

[[example]]
name = "basic"