[package]
name = "licensekey_handler"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
log = { workspace = true }

acap-logging = { workspace = true }
licensekey = { workspace = true }
