[package]
name = "licensekey"
version = "0.0.0"
edition.workspace = true
license = "MIT"

[dependencies]
glib-sys = { workspace = true }
libc = { workspace = true }
thiserror = { workspace = true }

licensekey-sys = { workspace = true }
