/* automatically generated by rust-bindgen 0.69.5 */

pub type DHErrorCode = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHError_t {
    _unused: [u8; 0],
}
pub type DHError = DHError_t;
extern "C" {
    pub fn dh_error_get_message(err: *const DHError) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_error_get_code(err: *const DHError) -> DHErrorCode;
}
extern "C" {
    pub fn dh_error_code_to_string(code: DHErrorCode) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_error_to_string(err: *const DHError) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_error_destroy(err: *mut DHError);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHTimestamp_t {
    _unused: [u8; 0],
}
pub type DHTimestamp = DHTimestamp_t;
extern "C" {
    pub fn dh_timestamp_create() -> *mut DHTimestamp;
}
extern "C" {
    pub fn dh_timestamp_set_with_sec(timestamp: *mut DHTimestamp, seconds: i64);
}
extern "C" {
    pub fn dh_timestamp_set_with_ms(timestamp: *mut DHTimestamp, milliseconds: i64);
}
extern "C" {
    pub fn dh_timestamp_set_current(timestamp: *mut DHTimestamp);
}
extern "C" {
    pub fn dh_timestamp_get_as_sec(timestamp: *const DHTimestamp) -> i64;
}
extern "C" {
    pub fn dh_timestamp_get_as_ms(timestamp: *const DHTimestamp) -> i64;
}
extern "C" {
    pub fn dh_timestamp_destroy(timestamp: *mut DHTimestamp);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHTopic_t {
    _unused: [u8; 0],
}
pub type DHTopic = DHTopic_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHTopicData_t {
    _unused: [u8; 0],
}
pub type DHTopicData = DHTopicData_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHInstanceKeys_t {
    _unused: [u8; 0],
}
pub type DHInstanceKeys = DHInstanceKeys_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHTopicInstance_t {
    _unused: [u8; 0],
}
pub type DHTopicInstance = DHTopicInstance_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHTopicSample_t {
    _unused: [u8; 0],
}
pub type DHTopicSample = DHTopicSample_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHTopicList_t {
    _unused: [u8; 0],
}
pub type DHTopicList = DHTopicList_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHTopicInstanceList_t {
    _unused: [u8; 0],
}
pub type DHTopicInstanceList = DHTopicInstanceList_t;
extern "C" {
    pub fn dh_topic_get_name(topic: *const DHTopic) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_topic_get_json_definition(
        topic: *const DHTopic,
        error: *mut *mut DHError,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_topic_destroy(topic: *mut DHTopic);
}
extern "C" {
    pub fn dh_topic_data_create() -> *mut DHTopicData;
}
extern "C" {
    pub fn dh_topic_data_destroy(topic_data: *mut DHTopicData);
}
extern "C" {
    pub fn dh_topic_data_set_json_data(
        topic_data: *mut DHTopicData,
        json_str: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_topic_data_get_json_data(
        topic_data: *const DHTopicData,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_topic_sample_get_topic_name(
        topic_sample: *const DHTopicSample,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_topic_sample_get_sample_id(topic_sample: *const DHTopicSample) -> u64;
}
extern "C" {
    pub fn dh_topic_sample_is_historical(topic_sample: *const DHTopicSample) -> bool;
}
extern "C" {
    pub fn dh_topic_sample_get_timestamp(topic_sample: *const DHTopicSample) -> *const DHTimestamp;
}
extern "C" {
    pub fn dh_topic_sample_get_data(topic_sample: *const DHTopicSample) -> *const DHTopicData;
}
extern "C" {
    pub fn dh_instance_keys_create() -> *mut DHInstanceKeys;
}
extern "C" {
    pub fn dh_instance_keys_destroy(keys: *mut DHInstanceKeys);
}
extern "C" {
    pub fn dh_instance_keys_add_string(
        keys: *mut DHInstanceKeys,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_instance_keys_add_integer(
        keys: *mut DHInstanceKeys,
        name: *const ::std::os::raw::c_char,
        value: i64,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_instance_keys_has_key(
        keys: *const DHInstanceKeys,
        name: *const ::std::os::raw::c_char,
    ) -> bool;
}
extern "C" {
    pub fn dh_instance_keys_get_string(
        keys: *const DHInstanceKeys,
        name: *const ::std::os::raw::c_char,
        out_value: *mut *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_instance_keys_get_integer(
        keys: *const DHInstanceKeys,
        name: *const ::std::os::raw::c_char,
        out_value: *mut i64,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_instance_keys_remove(
        keys: *mut DHInstanceKeys,
        name: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_topic_instance_get_topic_name(
        topic_instance: *const DHTopicInstance,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_topic_instance_get_keys(
        topic_instance: *const DHTopicInstance,
    ) -> *const DHInstanceKeys;
}
extern "C" {
    pub fn dh_topic_instance_get_info(
        topic_instance: *const DHTopicInstance,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_topic_instance_destroy(topic_instance: *mut DHTopicInstance);
}
extern "C" {
    pub fn dh_topic_list_get_count(list: *const DHTopicList) -> u32;
}
extern "C" {
    pub fn dh_topic_list_get_name(
        list: *const DHTopicList,
        index: u32,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_topic_list_destroy(topic_list: *mut DHTopicList);
}
extern "C" {
    pub fn dh_topic_instance_list_get_count(list: *const DHTopicInstanceList) -> u32;
}
extern "C" {
    pub fn dh_topic_instance_list_get(
        list: *const DHTopicInstanceList,
        index: u32,
    ) -> *const DHTopicInstance;
}
extern "C" {
    pub fn dh_topic_instance_list_destroy(instance_list: *mut DHTopicInstanceList);
}
pub type DHConsumerMatchStatus = u32;
pub type DHProductionId = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHWriter_t {
    _unused: [u8; 0],
}
pub type DHWriter = DHWriter_t;
pub type DHOnConsumerMatchUpdateCallback = ::std::option::Option<
    unsafe extern "C" fn(
        production_id: DHProductionId,
        status: DHConsumerMatchStatus,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
extern "C" {
    pub fn dh_writer_destroy(writer: *mut DHWriter);
}
extern "C" {
    pub fn dh_writer_set_consumer_match_update_callback(
        writer: *mut DHWriter,
        callback: DHOnConsumerMatchUpdateCallback,
        user_data: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn dh_writer_get_name(writer: *const DHWriter) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_writer_get_topic_name(writer: *const DHWriter) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_writer_write_data(
        writer: *mut DHWriter,
        instance_keys: *const DHInstanceKeys,
        topic_data: *const DHTopicData,
        timestamp: *const DHTimestamp,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_writer_create_instance(
        writer: *mut DHWriter,
        instance_keys: *const DHInstanceKeys,
        instance_info: *const ::std::os::raw::c_char,
        delete_on_disconnect: bool,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_writer_delete_instance(
        writer: *mut DHWriter,
        instance_keys: *const DHInstanceKeys,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_writer_delete_all_instances(writer: *mut DHWriter, error: *mut *mut DHError) -> bool;
}
extern "C" {
    pub fn dh_writer_register_production(
        writer: *mut DHWriter,
        instance_keys: *const DHInstanceKeys,
        production_id: *mut DHProductionId,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_writer_unregister_production(
        writer: *mut DHWriter,
        production_id: DHProductionId,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_writer_get_consumer_match_status(
        writer: *mut DHWriter,
        production_id: DHProductionId,
        status: *mut DHConsumerMatchStatus,
        error: *mut *mut DHError,
    ) -> bool;
}
pub type DHTopicUpdateType = u32;
pub type DHTopicInstanceUpdateType = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHSubscriber_t {
    _unused: [u8; 0],
}
pub type DHSubscriber = DHSubscriber_t;
pub type DHOnTopicUpdateCallback = ::std::option::Option<
    unsafe extern "C" fn(
        topic_name: *const ::std::os::raw::c_char,
        update_type: DHTopicUpdateType,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type DHOnInstanceUpdateCallback = ::std::option::Option<
    unsafe extern "C" fn(
        topic_instance: *const DHTopicInstance,
        update_type: DHTopicInstanceUpdateType,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type DHOnDataCallback = ::std::option::Option<
    unsafe extern "C" fn(
        topic_sample: *const DHTopicSample,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHFilter_t {
    _unused: [u8; 0],
}
pub type DHFilter = DHFilter_t;
extern "C" {
    pub fn dh_filter_create() -> *mut DHFilter;
}
extern "C" {
    pub fn dh_filter_destroy(filter: *mut DHFilter);
}
extern "C" {
    pub fn dh_filter_add_topic_name(
        filter: *mut DHFilter,
        topic_name: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_filter_add_instance(
        filter: *mut DHFilter,
        instance_keys: *const DHInstanceKeys,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_filter_add_data_expression(
        filter: *mut DHFilter,
        data_expression: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> bool;
}
pub type DHStartFrom = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHSubscribeOptions_t {
    _unused: [u8; 0],
}
pub type DHSubscribeOptions = DHSubscribeOptions_t;
extern "C" {
    pub fn dh_subscribe_options_create() -> *mut DHSubscribeOptions;
}
extern "C" {
    pub fn dh_subscribe_options_destroy(options: *mut DHSubscribeOptions);
}
extern "C" {
    pub fn dh_subscribe_options_add_filter(
        options: *mut DHSubscribeOptions,
        filter: *const DHFilter,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_subscribe_options_set_enable_topic_updates(
        options: *mut DHSubscribeOptions,
        enable: bool,
    );
}
extern "C" {
    pub fn dh_subscribe_options_set_enable_instance_updates(
        options: *mut DHSubscribeOptions,
        enable: bool,
    );
}
extern "C" {
    pub fn dh_subscribe_options_set_enable_data_updates(
        options: *mut DHSubscribeOptions,
        enable: bool,
    );
}
extern "C" {
    pub fn dh_subscribe_options_set_start_from(
        options: *mut DHSubscribeOptions,
        start_from: DHStartFrom,
    );
}
extern "C" {
    pub fn dh_subscriber_destroy(subscriber: *mut DHSubscriber);
}
extern "C" {
    pub fn dh_subscriber_get_name(subscriber: *const DHSubscriber)
        -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_subscriber_set_topic_update_callback(
        subscriber: *mut DHSubscriber,
        on_topic_update: DHOnTopicUpdateCallback,
        user_data: *mut ::std::os::raw::c_void,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_subscriber_set_instance_update_callback(
        subscriber: *mut DHSubscriber,
        on_instance_update: DHOnInstanceUpdateCallback,
        user_data: *mut ::std::os::raw::c_void,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_subscriber_set_data_callback(
        subscriber: *mut DHSubscriber,
        on_data: DHOnDataCallback,
        user_data: *mut ::std::os::raw::c_void,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_subscriber_subscribe(
        subscriber: *mut DHSubscriber,
        options: *const DHSubscribeOptions,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_subscriber_unsubscribe(
        subscriber: *mut DHSubscriber,
        error: *mut *mut DHError,
    ) -> bool;
}
pub type DHConnectionState = u32;
pub type DHLogLevel = u32;
pub type DHLogTarget = u32;
pub type DHOnConnectionUpdateCallback = ::std::option::Option<
    unsafe extern "C" fn(update: DHConnectionState, user_data: *mut ::std::os::raw::c_void),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DHClient_t {
    _unused: [u8; 0],
}
pub type DHClient = DHClient_t;
extern "C" {
    pub fn dh_client_create(
        name: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> *mut DHClient;
}
extern "C" {
    pub fn dh_client_get_name(client: *const DHClient) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn dh_client_set_connection_update_callback(
        client: *mut DHClient,
        callback: DHOnConnectionUpdateCallback,
        user_data: *mut ::std::os::raw::c_void,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_client_connect(client: *mut DHClient, error: *mut *mut DHError) -> bool;
}
extern "C" {
    pub fn dh_client_disconnect(client: *mut DHClient, error: *mut *mut DHError) -> bool;
}
extern "C" {
    pub fn dh_client_destroy(client: *mut DHClient);
}
extern "C" {
    pub fn dh_client_get_connection_state(client: *const DHClient) -> DHConnectionState;
}
extern "C" {
    pub fn dh_client_create_topic_from_file(
        client: *mut DHClient,
        file_path: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> *mut DHTopic;
}
extern "C" {
    pub fn dh_client_create_topic(
        client: *mut DHClient,
        topic_def: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> *mut DHTopic;
}
extern "C" {
    pub fn dh_client_delete_topic(
        client: *mut DHClient,
        topic_name: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> bool;
}
extern "C" {
    pub fn dh_client_get_topic_list(
        client: *mut DHClient,
        error: *mut *mut DHError,
    ) -> *mut DHTopicList;
}
extern "C" {
    pub fn dh_client_get_topic(
        client: *mut DHClient,
        topic_name: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> *mut DHTopic;
}
extern "C" {
    pub fn dh_client_get_topic_instances(
        client: *mut DHClient,
        topic_name: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> *mut DHTopicInstanceList;
}
extern "C" {
    pub fn dh_client_create_writer(
        client: *mut DHClient,
        writer_name: *const ::std::os::raw::c_char,
        topic_name: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> *mut DHWriter;
}
extern "C" {
    pub fn dh_client_create_subscriber(
        client: *mut DHClient,
        subscriber_name: *const ::std::os::raw::c_char,
        error: *mut *mut DHError,
    ) -> *mut DHSubscriber;
}
extern "C" {
    pub fn dh_client_set_logging(
        client: *mut DHClient,
        level: DHLogLevel,
        target: DHLogTarget,
        error: *mut *mut DHError,
    ) -> bool;
}
