name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dev container dependencies
        run: npm install -g @devcontainers/cli@0.65.0
      - name: Run checks in dev container
        run: |
          devcontainer up --workspace-folder .
          devcontainer exec --workspace-folder . make --always-make check_all
          devcontainer exec --workspace-folder . make build AXIS_PACKAGE=licensekey_handler
          devcontainer exec --workspace-folder . make build AXIS_PACKAGE=embedded_web_page
      - name: Install host dependencies
        run: cargo install cross
      - name: Run checks on host
        run: |
          make check_all
