name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: cargo install cross
      - name: Run checks
        run: |
          make --always-make check_all
          PACKAGE=licensekey_handler make build
