[package]
name = "larod"
version = "0.1.0"
edition.workspace = true

[dependencies]

larod-sys = { workspace = true }
log.workspace = true
thiserror.workspace = true

[features]
device-tests = []

[[example]]
name = "basic"