[package]
name = "larod"
version = "0.1.0"
edition.workspace = true

[dependencies]

larod-sys = { workspace = true }
log.workspace = true
thiserror.workspace = true

[dev-dependencies]
env_logger.workspace = true
trybuild = "1.0.101"

[features]
device-tests = []

[[example]]
name = "basic"